[workspace]
resolver = "2"
members = [
    "happ/zomes/projects",
    "happ/zomes/projects_core",
    "happ/zomes/profiles",
    "happ/zomes/profiles_core",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
