[package]
edition = "2018"
name = "projects"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "projects"

[dependencies]
holo_hash = { version = "=0.0.19", features = ["encoding", "fixturators"] }
hdk = {version = "0.0.122", features = ["encoding"]}
chrono = {version = "0.4", features = ['alloc', 'std']}
derive_more = "0.99"
serde = "*"
paste = "*"
tracing = "0.1.26"
