name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - name: Use Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure Nix substituters
        run: |
          set -xe
          mkdir -p ~/.config/nix/
          cp ./.github/nix.conf ~/.config/nix/
      - uses: cachix/cachix-action@v10
        with:
          name: holochain-ci
      - name: Prepare Nix environment
        run: nix-shell --command "echo Completed"
      - name: Install PNPM and root dependencies
        run: nix-shell --command "pnpm install --no-frozen-lockfile"
      - name: Install PNPM and UI dependencies
        run: nix-shell --command "pnpm run  web-install"
      - name: Build webhApp
        run: |
          nix-shell --command "pnpm run webhapp-pack"
      - name: upload webhapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "workdir/application.webhapp" --clobber
