
name: Tryorama tests

on: [ pull_request ]

jobs:
  tryorama_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2
    - name: Use Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure Nix substituters
      run: |
        set -xe
        mkdir -p ~/.config/nix/
        cp ./.github/nix.conf ~/.config/nix/
    - uses: cachix/cachix-action@v10
      with:
        name: holochain-ci
    - name: Prepare Nix environment
      run: nix-shell --command "echo Completed"
    - name: Install deps
      run: nix-shell --command "pnpm run install-deps"
    - name: check hc
      run: nix-shell --command "holochain --build-info"
    - name: build happ
      run: nix-shell --command "pnpm run hc:happ-pack"
    - name: Run all tests
      run: nix-shell --command "pnpm run test"